[package]
name = "ufp_ingest"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.17"
tracing = "0.1"
uuid = { version = "1", features = ["serde", "v4", "v5"] }
