[package]
name = "ufp_canonical"
version = "0.1.0"
edition = "2024"


[dependencies]
unicode-normalization = "0.1"
unicode_categories = "0.1"
sha2 = "0.10"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
